Vagrant.configure("2") do |config|
config.vm.define "maquina_1" do |m1|
m1.vm.box = "ubuntu/jammy64"
m1.vm.network "private_network",
ip: "192.168.20.1"
# provisioning si aloja un servicio
end
config.vm.define "maquina_2" do |m2|
m2.vm.box = "ubuntu/jammy64"
m2.vm.network "private_network",
ip: "192.168.20.2"
end
end