Vagrant.configure("2") do |config| 
    config.vm.define "maquina_1" do |m1|
        m1.vm.box = "ubuntu/jammy64" 
        m1.vm.network "private_network", 
        ip: "192.168.20.1",
        virtualbox__intnet: true
    
    m1.vm.provider "virtualbox" do |vb| 
        vb.memory = 2048 
        vb.cpus = 1 
    end

    m1.vm.provision "shell",
        path: "provisioning.sh" 
    end


    config.vm.define "maquina_2" do |m2|
        m2.vm.box = "ubuntu/jammy64"
        m2.vm.network "private_network",
        ip: "192.168.20.2",
        virtualbox__intnet: true
        
        m2.vm.provider "virtualbox" do |vb| 
            vb.memory = 2048 
            vb.cpus = 1 
        end
    
        m2.vm.provision "shell",
            path: "provisioning.sh" 
        end
end