Vagrant.configure("2") do |config|
config.vm.box = "ubuntu/jammy64"
config.vm.network "private_network",
ip: "192.168.20.1"
config.vm.provider "virtualbox" do |vb|
vb.memory = 2048
vb.cpus = 1
end
config.vm.provision "shell",
path: "provisioning.sh"
end